# Site
repository: Bill1119/Bill1119.github.io
favicon: images/favicon.ico

# Personal info
name: Che-Shao(Bill) Chen
title: Master Student in Concordia University
email: bill1119@hotmail.com
website: www.github.com/Bill1119/Bill1119.github.io

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A master student in software engineering, who is looking for an internship/full-time position as a software developer/tester. 

  I am most skilled in: <mark>JAVA</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# More Section
# more_title: TECHNICAL SKILLS 
# more_content: | # this will include new lines to allow paragraphs
# * indicates the level of experience (*** - advanced               ** - intermediate               * -basic )
# Programming Development Web Database Others 
#    Java ​*** Eclipse ​*** Flask ​** ER Diagram ​** UML ​** 
#    Python ​** Anaconda ​** React ​** Spark ​** Windows ​** 
#    R ​* Bash ​** HTML/CSS ​* MySQL ​* Linux ​** 
#    JavaScript ​* JetBrains ​**  SQLite​ * JUnit ​** 
#    C# ​* GitHub ​**   Keras ​* * 
# # Footer
# footer_show_references: true

# # Build settings
# remote_theme: sproogen/resume-theme

# sass:
#   sass_dir: _sass
#   style: compressed

# plugins:
#  - jekyll-seo-tag
