# Site
repository: Bill1119/Bill1119.github.io
favicon: images/favicon.ico

# Personal info
name: Che-Shao(Bill) Chen
title: Master Student in Concordia University
email: bill1119@hotmail.com
website: www.github.com/Bill1119

# Social links
# twitter_username: facespics
# github_username:  sproogen
# # dribbble_username: jekyll
# # facebook_username: jekyll
# # flickr_username: jekyll
# instagram_username: chillwildlife
 linkedin_username: Che Shao Chen
# # pinterest_username: jekyll
# youtube_username: globalmtb
# # googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A master student in software engineering, who is looking for an internship/full-time position as a software developer/tester. 

  I am most skilled in: <mark>JAVA</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: Bill1119/Bill1119.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
